config/routes.rb
Rails.application.routes.draw do

  concern :searchable do
    get :search, on: :collection
  end

  resources :record_types, as: :categories, path: :categories, concerns: :searchable do

    resources :field_metadata, as: :fields, path: :fields, only: :destroy

  end

  root 'application#index', via: [:get, :post] # TODO This needs to be improved, but for now it's OK

end

app/models/decimal_value.rb
class DecimalValue < ActiveRecord::Base

  belongs_to :field

  validates :value, presence:     { message: 'Value is required and cannot be empty.' },
                    numericality: { message: "'%{value}' is not a decimal number." }
  validates :field_id, presence: true

end

app/models/field.rb
class Field < ActiveRecord::Base

  # *** TODO ***
  # Implement API to expose a single value attribute for read/write and hide
  # decimal_value, integer_value, string_value, timestamp_value
  has_one :decimal_value, dependent: :delete
  has_one :integer_value, dependent: :delete
  has_one :string_value, dependent: :delete
  has_one :timestamp_value, dependent: :delete
  belongs_to :record
  belongs_to :metadata, class_name: 'FieldMetadata', foreign_key: :field_metadata_id

  validates :record_id, presence: true
  validates :field_metadata_id, presence: true

end

app/models/field_metadata.rb
class FieldMetadata < ActiveRecord::Base

  belongs_to :record_type
  has_many :fields, dependent: :restrict_with_exception

  validates :field_name, presence:   { message: 'Name is required and cannot be empty.' },
                         uniqueness: { scope: :record_type, message: "'%{value}' is already taken. Try a new one.", on: :create },
                         length:     { within: 2..100,
                                       too_short: 'Name is too short. Try again using at least 2 characters.',
                                       too_long: 'Name is too long. Try again using less than 100 characters.'
                                     }

  validates :record_type, presence: true

end

app/models/integer_value.rb
class IntegerValue < ActiveRecord::Base

  belongs_to :field

  validates :value, presence:     { message: 'Value is required and cannot be empty.' },
                    numericality: { only_integer: true, message: "'%{value}' is not an integer." }
  validates :field_id, presence: true

end

app/models/record.rb
class Record < ActiveRecord::Base

  belongs_to :record_type
  has_many   :fields, { dependent: :delete_all }

  validates :record_type_id, presence: true

end

app/models/record_type.rb
class RecordType < ActiveRecord::Base

  has_many :records, dependent: :restrict_with_exception
  has_many :metadata, inverse_of: :record_type, class_name: 'FieldMetadata', dependent: :delete_all

  validates :name, presence:   { message: 'Name is required and cannot be empty.' },
                   uniqueness: { message: "'%{value}' is already taken. Try a new one." },
                   length:     { within: 4..20,
                                 too_short: 'Name is too short. Try again using at least 4 characters.',
                                 too_long: 'Name is too long. Try again using less than 20 characters.'
                               }

  validate :metadata_presence

  accepts_nested_attributes_for :metadata

  def records_count
    records.count
  end

  private

    def metadata_presence
      errors.add(:metadata, 'At least one field is required.') if metadata.size == 0
    end

end

app/models/string_value.rb
class StringValue < ActiveRecord::Base

  belongs_to :field

  validates :value, presence: { message: 'Value is required and cannot be empty.' },
                    length:   { within: 0..65_515,
                                too_long: 'Value is too long. Try again using less than 65515 characters.'
                              }
  validates :field_id, presence: true

end

app/models/timestamp_value.rb
class TimestampValue < ActiveRecord::Base

  belongs_to :field

  validates :value, presence: { message: 'Value is required and cannot be empty.' }
  validates :field_id, presence: true
  validate  :is_a_valid_datetime

  def value= value
    # *** TODO *** let's ignore for now datetime formats and locales
    write_attribute :value, (value.to_datetime rescue nil)
  end

  protected

    def is_a_valid_datetime
      value.to_datetime rescue errors.add :value, "'%{value}' is not a valid date or time value."
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    if request.post?
      redirect_to categories_path
    end
  end

  def search
    # TODO In the future, it's very likely that we'll implement this
    # functionality as a concern. Inheritance is fine for now.
  end
end

app/controllers/field_metadata_controller.rb
class FieldMetadataController < ApplicationController

  def destroy
    respond_to do |format|
      begin
        @category = RecordType.find params[:category_id]
        @category.metadata.find(params[:id]).destroy
        format.json { render json: { message: 'Field deleted!' }.to_json, status: :ok }
      rescue Exception => e
        message   = "Can't delete. There are records having this field." if e.instance_of? ActiveRecord::DeleteRestrictionError
        message ||= 'Oops! Something unexpected happened.'
        format.json { render json: { message: message }.to_json, status: :sever_error }
      end
    end
  end

end

app/controllers/record_types_controller.rb
class RecordTypesController < ApplicationController

  layout 'member'

  before_action :filter_out_blank_field_names, only: [:create, :update]

  def new
    @category = RecordType.new
    @category.metadata.build
  end

  def create
    @category = RecordType.new category_params
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def index
    @categories = RecordType.all.order :name
  end

  def show
    # TODO 
    @category = RecordType.find params[:id]
  end

  def edit
    @category = RecordType.find params[:id]
  end

  def update
    @category = RecordType.find params[:id]
    if @category.update category_params
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    respond_to do |format|
      begin
        @category = RecordType.find params[:id]
        @category.destroy
        format.json { render json: { message: 'Record deleted!' }.to_json, status: :ok }
      rescue Exception => e
        message   = "Can't delete. Category has records." if e.instance_of? ActiveRecord::DeleteRestrictionError
        message ||= 'Oops! Something unexpected happened.'
        format.json { render json: { message: message }.to_json, status: :sever_error }
      end
    end
  end

  def search
    @categories = RecordType.where('name like :name', name: "%#{params[:keyword]}%").order :name
    render layout: false
  end


  private

    def category_params
      params.require(:category)
            .permit(:name, metadata_attributes: [ :id,  :field_name ])
    end

    def filter_out_blank_field_names
      if params[:category].has_key? :metadata_attributes
       params[:category][:metadata_attributes].delete_if { |k,v| v[:field_name].blank? }
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def field_errors model, field
    errors = model.errors
    return unless errors and errors.has_key? field
    items = []
    errors[field].each do |error_message|
      items << %Q|<li class="error">#{error_message}</li>|
    end
    %Q|<ul class="errors">#{items.join ''}</ul>|.html_safe
  end
end

app/helpers/record_types_helper.rb
module RecordTypesHelper
end

app/views/application/index.html.erb
<div class="landing">
  <div class="centered-box">
    <div class="content">
      <div class="container">
        <div class="row">
          <div class="marketing col-xs-12 col-sm-4">
            <h1>Archie</h1> 
            <p>Archie everything!</p>
          </div>
          <div class="user-access col-xs-12 col-sm-8">
            <%= form_tag '' %> 
              <div class="form-group">
                <%= label_tag :username %> 
                <%= text_field_tag :username, nil, class: 'form-control' %>
              </div> 
              <div class="form-group">
                <%= label_tag :password %>
                <%= password_field_tag :password, nil, class: 'form-control' %>
              </div>
              <%= button_tag 'Log In', class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div> 
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, minimum-scale=1" />
    <title>Archie</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <main><%= yield %></main>
    <footer><%= "jmirandase © #{Time.now.year}" %></footer>
  </body>
</html>

app/views/layouts/member.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0" />
    <title>Archie</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <ul class="menu">
        <li class="item">
          <%= link_to content_tag(:span, nil, class: 'glyphicon glyphicon-home'), categories_path, class: 'action', title: 'Home' %> 
        </li>
        <li class="item">
          <%= link_to content_tag(:span, nil, class: 'glyphicon glyphicon-plus'), new_category_path, class: 'action', title: 'New' %> 
        </li>
      </ul>  
    </header> 
    <main><%= yield %></main>
  </body>
</html>

app/views/record_types/_form.html.erb
<%= form_for category, url: action_path, as: :category, html: { class: 'horizontal-form new-category' } do |f| %>
  <fieldset class="category">
    <legend>Categories</legend>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
      <%= field_errors category, :name %>
    </div>
  </fieldset>
  <fieldset class="metadata">
    <legend>
      <span>Fields</span>
      <%= button_tag type: :button, class: 'btn btn-action add', title: 'Add' do %>
        <%= content_tag :span, nil, class: 'glyphicon glyphicon-plus' %>
      <% end %>
    </legend>
  <% category.metadata.each do |metadata| %>
    <div class="form-group">
      <%= f.fields_for :metadata, metadata do |metadata_fields| %>
          <%= metadata_fields.text_field :field_name, class: 'form-control', placeholder: 'Field Name', id: nil %>
          <%= button_tag type: :button, class: 'btn btn-action remove', title: 'Delete',
                         data: { id: (metadata_fields.object.id || 0) } do %>
            <%= content_tag :span, nil, class: 'glyphicon glyphicon-remove' %>
          <% end %>
      <% end %>
      <%= field_errors metadata, :field_name %>
    </div>
  <% end %>
    <%= field_errors category, :metadata %>
  </fieldset>
  <%= f.button 'Save', name: nil, class: 'btn btn-primary btn-action' %>
<% end %>

app/views/record_types/edit.html.erb
<div class="categories">
  <div class="container">
    <div class="row">
      <%= render 'form', category: @category, action_path: category_path(@category) %> 
    </div>
  </div>
</div>

app/views/record_types/index.html.erb
<div class="categories">
  <div class="container">
    <div class="row">
      <%= render 'shared/search_box', search_path: search_categories_path %>
    </div>
    <div class="row">
      <div class="search-results col-xs-12">
        <ol class="data">
        <% @categories.each do |category| %>
          <li class="item">
            <div class="action">
              <%= button_tag 'C', type: 'button', data: { id: category.id }%>
            </div>
            <div class="excerpt">
              <h2><%= category.name %></h2>
              <div class="fields">
                <span class="field col-xs-12">
                  <%= pluralize category.records_count, 'record' %>
                </span>
              </div>
            </div>
          </li>
        <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>
<div class="actions-bar animatable">
  <ul class="menu">
    <li class="item">
    <%= link_to content_tag(:span, nil, class: 'glyphicon glyphicon-plus'), new_category_path, class: 'action', title: 'New' %>
    </li>
    <li class="item">
    <%= link_to content_tag(:span, nil, class: 'glyphicon glyphicon-edit'), '', class: 'action edit', title: 'Edit' %>
    </li>
    <li class="item">
    <%= button_to nil, { method: :delete, class: 'action', title: 'Delete',
                         remote: true, form: { class: 'action delete', data: { type: :json } } } do %>
      <%= content_tag :span, nil, class: 'glyphicon glyphicon-remove' %>
    <% end %>
    </li>
  </ul>
</div> 

app/views/record_types/new.html.erb
<div class="categories">
  <div class="container">
    <div class="row">
      <%= render 'form', category: @category, action_path: categories_path %>
    </div>
  </div>
</div>

app/views/record_types/search.html.erb
<% @categories.each do |category| %>
  <li class="item">
    <div class="action">
      <%= button_tag 'C', type: 'button' %>
    </div>
    <div class="excerpt">
      <h2><%= category.name %></h2>
      <div class="fields">
        <span class="field col-xs-12">
          <%= pluralize category.records_count, 'record' %>
        </span>
      </div>
    </div>
  </li>
<% end %>

app/views/record_types/show.html.erb
<h1>RecordTypes#show</h1>
<p>Find me in app/views/record_types/show.html.erb</p>

app/views/shared/_search_box.html.erb
<div class="search-box col-xs-12">
<%= form_tag search_path, method: :get, class: 'form-inline', remote: true, id: 'search-form' do %>
  <div class="form-group">
    <%= label_tag :keyword, nil, class: 'sr-only' %>
    <div class="input-group">
      <%= text_field_tag :keyword, nil, class: 'form-control', placeholder: 'Search...' %>
      <div class="input-group-addon btn-container">
        <%= button_tag name: nil do %>
          <%= content_tag :span, nil, class: 'glyphicon glyphicon-search' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>